"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

[package]
disabled = true

[character]
success_symbol = '[ ](bold #d27e99)[ ](bold #e6c384)[ ](bold #a3d4d5)[  ](bold #98bb6c)'
error_symbol = '[ ](bold #d27e99)[ ](bold #e6c384)[ ](bold #a3d4d5)[  ](bold #ff5d62)'
vimcmd_symbol = '[ NORMAL](bold #ffa066)'
vimcmd_visual_symbol = '[ VISUAL](bold #957fb8)'

[git_branch]
symbol = ' '

[git_status]
modified = ''
untracked = ''
staged = ''

[nodejs]
disabled = true
